---
kind: pipeline
name: Ubuntu 22.04
type: vm
pool:
  use: ubuntu-22.04
clone: 0

steps:
  - name: Install Panel
    commands:
      - wget https://raw.githubusercontent.com/PanelOmega/Panel/main/installers/install.sh && chmod +x install.sh && ./install.sh
