---
kind: pipeline
name: Ubuntu 22.04
type: vm
platform:
  os: linux
  arch: amd64
  version: 22.04
spec:
  ami: ami-051197ce9cbb023ea
  size: t2.nano

steps:
  - name: greeting
    commands:
      - echo hello world
