---
kind: pipeline
name: Ubuntu 22.04
type: amazon
platform:
  os: linux
  arch: amd64
  version: 22.04
  ami: ami-0a50f993202fe4f22
spec:
  ami: ami-0a50f993202fe4f22
  size: t2.nano

steps:
  - name: greeting
    commands:
      - echo hello world
