---
kind: pipeline
name: Ubuntu 22.04 - Unit Test & Code Coverage
type: vm
pool:
  use: ubuntu-22.04

steps:
  - name: run
    environment:
      DEBIAN_FRONTEND: noninteractive
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - MAIN_REPO_DIR=$(pwd)
      - ls -la
      - cd $MAIN_REPO_DIR/web
      
#      - apt-get update
#      - apt-get install -yq libicu-dev sudo cron apt-utils daemonize dbus-user-session fontconfig rsync
#      - daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target
#
#      - mkdir /omega-panel
#
#      - cp $MAIN_REPO_DIR/installers/ubuntu-22.04/install-partial/install_base.sh /omega-panel/install_base.sh
#      - chmod +x /omega-panel/install_base.sh
#      - cp $MAIN_REPO_DIR/installers/ubuntu-20.04/install-partial/install_web.sh /omega-panel/install_web.sh
#      - chmod +x /omega-panel/install_web.sh
#
#      - /omega-panel/install_base.sh
#
#      - cp -r $MAIN_REPO_DIR/web /usr/local/omega/web/
#      - ls -la
#      - cd /usr/local/omega/web/
#      - ls -la
#
#      - wget https://getcomposer.org/download/latest-stable/composer.phar
#      - COMPOSER_ALLOW_SUPERUSER=1 omega-php composer.phar install
#
#      - /omega-panel/install_web.sh
#
#      - apt-get install autoconf build-essential -y
#      - mkdir -p /usr/local/omega/php-xdebug
#      - cd /usr/local/omega/php-xdebug
#      - wget http://xdebug.org/files/xdebug-3.3.2.tgz
#      - tar -xvzf xdebug-3.3.2.tgz
#      - cd xdebug-3.3.2
#      - /usr/local/omega/php/bin/phpize
#      - ./configure --enable-xdebug --with-php-config=/usr/local/omega/php/bin/php-config
#      - make
#
#      - mkdir -p /usr/local/omega/php/zend-xdebug
#      - cp modules/xdebug.so /usr/local/omega/php/zend-xdebug/xdebug.so
#
#      - chmod 777 /usr/local/omega/php/zend-xdebug/xdebug.so
#
#      - cp /usr/local/omega/web/tests/Configs/xDebugPHP.ini /usr/local/omega/php/bin/php.ini
#
#      - chmod 777 /usr/local/omega/php/bin/php.ini
#      - omega-php -v
#
#      - cd /usr/local/omega/web/
#      - chmod -R 777 vendor
#      - apt install composer -y
#      - omega-php artisan omega:set-ini-settings APP_ENV "local"
#      - composer test:coverage
#      - mv clover.xml $MAIN_REPO_DIR/clover.xml
#      - mv coverage.xml $MAIN_REPO_DIR/coverage.xml
#      - cd $MAIN_REPO_DIR
#      - apt install -yq pip
#      - pip install codecov-cli
#      - codecovcli --verbose upload-process -t $CODECOV_TOKEN
#
#---
#kind: pipeline
#name: e2e Test - Ubuntu 22.04
#type: vm
#pool:
#  use: ubuntu-22.04
#
#clone:
#  disable: true
#
#steps:
#  - name: Install Panel
#    commands:
#      - wget https://raw.githubusercontent.com/PanelOmega/Panel/main/installers/install.sh && chmod +x install.sh && ./install.sh
