---
kind: pipeline
type: digitalocean
name: Ubuntu 22.04
token:
  from_secret: token

server:
  image: ubuntu-22-04-x64
  size: s-2vcpu-2gb
  region: nyc1

steps:
  - name: greeting
    commands:
      - echo hello world
