---
kind: pipeline
name: Ubuntu 22.04 - Unit Test & Code Coverage
type: vm
pool:
  use: ubuntu-22.04

steps:
  - name: run
    environment:
      DEBIAN_FRONTEND: noninteractive
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - MAIN_REPO_DIR=$(pwd)
      - apt-get update
      - apt-get install -yq libicu-dev sudo cron apt-utils daemonize dbus-user-session fontconfig rsync
      - daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target

      - ls -la
      - mkdir /omega-panel

      - cd $MAIN_REPO_DIR
      - ls -la
