# Generated by NetworkManager
@if(isset($bind9Nameservers))

@foreach($bind9Nameservers as $nameServer)
nameserver {{ $nameServer }}
@endforeach

@endif
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
