name: Panel Omega - Unit Test & Build
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-server-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.sha }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: oci8, ssh2

      - name: Create Server & Run E2E Server Test
        run: |
          sudo apt install php8.2-ssh2 -y
          GITHUB_COMMIT_SHA=${{ github.sha }}
          GITHUB_REPOSITORY=${{ github.repository }}
          GITHUB_BRANCH=${{ github.ref }}
          cd e2e-server-test
          sudo wget https://getcomposer.org/download/latest-stable/composer.phar
          sudo COMPOSER_ALLOW_SUPERUSER=1 php composer.phar install
          sudo php run.php test --TEST_TYPE=commit --HETZNER_API_KEY=${{ secrets.HETZNER_API_KEY }} --GIT_REPO_URL=$GITHUB_REPOSITORY --GIT_BRANCH=$GITHUB_BRANCH --GIT_COMMIT=$GITHUB_COMMIT_SHA
          sudo php run.php test --TEST_TYPE=code-coverage --CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} --HETZNER_API_KEY=${{ secrets.HETZNER_API_KEY }} --GIT_REPO_URL=$GITHUB_REPOSITORY --GIT_BRANCH=$GITHUB_BRANCH --GIT_COMMIT=$GITHUB_COMMIT_SHA

  compile-and-publish:
    runs-on: ubuntu-22.04
    needs: e2e-server-test
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
      - name: Npm install
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer Dependencies
        working-directory: ./web
        run: |
          composer install
          composer dump-autoload

      - name: Install NODE Dependencies
        working-directory: ./web
        run: |
          npm install
          npm run build

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Zip the files
        working-directory: ./web
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf .nmp
          rm -rf node_modules
          rm -rf .phpunit.cache
          rm -rf vendor/composer/tmp-*.zip
          find . \( -name ".git" -o -name ".gitignore" -o -name ".gitmodules" -o -name ".gitattributes"  \) -exec rm -rf -- {} +
          zip -r panel-omega-web-build.zip `ls -A`
          mkdir -p ../dist
          mv ./panel-omega-web-build.zip ../dist/panel-omega-latest.zip

      - name: Pushes to PanelOmega WebCompiledVersions
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: './dist'
          destination-github-username: 'PanelOmega'
          destination-repository-name: 'WebCompiledVersions'
          user-email: bobicloudvision@gmail.com
          target-branch: main
